name: ESLint Check on Dev Push 

on:
  push:
    branches:
      - dev 

jobs:
  eslint-check: 
    runs-on: ubuntu-latest 

    steps:
      - name: Checkout code 
        uses: actions/checkout@v4 

      - name: Setup Node.js 
        uses: actions/setup-node@v4 
        with:
          node-version: '18.19' 

      - name: Install dependencies 
        run: npm install 

      - name: Run ESLint 
        run: npx eslint src/**/*.ts 